[platformio]
default_envs = simulator
boards_dir = boards

[env:simulator]
platform = platformio/native@1.2.1
build_type = debug
lib_deps =
    https://github.com/lvgl/lvgl/archive/refs/tags/v9.3.0.zip
build_flags =
    -std=c++17
    -arch x86_64
    -DLV_CONF_SKIP
    -DLV_USE_SDL=1
    -DLV_COLOR_DEPTH=16
    -DLV_MEM_SIZE=5242880U
    -DLV_FONT_MONTSERRAT_12=1
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_20=1
    !sdl2-config --cflags
    !sdl2-config --libs

[env:t-deck]
platform = espressif32@6.13.0
board = T-Deck
framework = arduino
build_type = release
extra_scripts = post:scripts/esp32_factory.py
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = default_16MB.csv
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -DLILYSHARK_DEVICE=1
    -DBOARD_HAS_PSRAM=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_SKIP
    -DLV_COLOR_DEPTH=16
    -DLV_MEM_SIZE=98304U
    -DLV_FONT_MONTSERRAT_12=1
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_20=1
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_RGB_ORDER=TFT_RGB
    -DINIT_SEQUENCE_2=1
    -DTFT_MISO=38
    -DTFT_MOSI=41
    -DTFT_SCLK=40
    -DTFT_CS=12
    -DTFT_DC=11
    -DTFT_RST=-1
    -DTFT_BL=42
    -DTFT_BACKLIGHT_ON=1
    -DLOAD_GLCD=1
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=20000000
lib_deps =
    https://github.com/lvgl/lvgl/archive/refs/tags/v9.3.0.zip
    bodmer/TFT_eSPI@2.5.43
    mikalhart/TinyGPSPlus@1.1.0
    jgromes/RadioLib@7.7.1
