[platformio]
default_envs = simulator

[env:simulator]
platform = platformio/native@1.2.1
build_type = debug
lib_deps =
    https://github.com/lvgl/lvgl/archive/refs/tags/v9.3.0.zip
build_flags =
    -std=c++17
    -arch x86_64
    -DLV_CONF_SKIP
    -DLV_USE_SDL=1
    -DLV_COLOR_DEPTH=16
    -DLV_MEM_SIZE=5242880U
    -DLV_FONT_MONTSERRAT_12=1
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_20=1
    !/usr/local/bin/sdl2-config --cflags
    !/usr/local/bin/sdl2-config --libs
