/**
 * PAPER — the whitepaper, and nothing else.
 *
 * The 63 pages are pre-rendered to WebP at build time (webapp/public/paper/,
 * regenerated by the pymupdf one-liner in the repo README whenever the PDF
 * changes) and shown as a plain column of lazy-loading images. Two runtime
 * viewers were tried first and both failed where it mattered: an <iframe>
 * cannot scroll a PDF at all on iOS Safari, and pdf.js stalled its worker
 * handshake in production. A static document does not need a runtime — images
 * scroll natively on every device, cost no JavaScript, and the browser only
 * fetches the pages the reader actually reaches.
 *
 * Every page shares one aspect ratio (baked into PAGE_RATIO below from the
 * render), so unloaded pages hold their exact final height and the scrollbar
 * tells the truth from the first frame.
 */

const PAGES = 63;
const PAGE_RATIO = 1812 / 1400; // height / width of the pre-rendered pages
const src = (n: number) => `/paper/page-${String(n).padStart(3, '0')}.webp`;

export function WhitepaperTab() {
  return (
    <main className="fill">
      <div className="pdf-scroll">
        <div className="pdf-toolbar">
          THE GROWTH TRAP IN PROOF OF PHYSICAL WORK · {PAGES} PP
          <span style={{ flex: 1 }} />
          <a href="/lilyshark-whitepaper.pdf" download="lilyshark-whitepaper.pdf">
            DOWNLOAD PDF
          </a>
        </div>
        {Array.from({ length: PAGES }, (_, i) => (
          <img
            key={i + 1}
            className="pdf-page"
            src={src(i + 1)}
            alt={`Page ${i + 1} of ${PAGES}`}
            width={1400}
            height={1812}
            loading={i < 2 ? 'eager' : 'lazy'}
            decoding="async"
            style={{ aspectRatio: `1400 / ${Math.round(1400 * PAGE_RATIO)}` }}
          />
        ))}
      </div>
    </main>
  );
}
