import {escapeHTML as e} from './catalog.mjs';
import {PILOT_FIELD_LIMITS,MEDIA_RIGHTS,PILOT_BUDGETS} from './pilot-brief.mjs';

const arrow='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>';
const options=items=>Object.entries(items).map(([value,label])=>`<option value="${e(value)}">${e(label)}</option>`).join('');
const field=(key,label,{type='text',placeholder='',required=false,multiline=false,help=''}={})=>`<div class="pilot-field"><label for="pilot-${key}">${label}${required?'':' <span>Optional</span>'}</label>${multiline?`<textarea id="pilot-${key}" name="${key}" rows="${key==='parts'?4:3}" maxlength="${PILOT_FIELD_LIMITS[key]}" placeholder="${e(placeholder)}"${required?' required':''} aria-describedby="pilot-${key}-error${help?` pilot-${key}-help`:''}"></textarea>`:`<input id="pilot-${key}" name="${key}" type="${type}" maxlength="${PILOT_FIELD_LIMITS[key]}" placeholder="${e(placeholder)}"${required?' required':''}${type==='url'?' autocapitalize="none" spellcheck="false"':''} aria-describedby="pilot-${key}-error${help?` pilot-${key}-help`:''}">`}${help?`<p class="pilot-field-help" id="pilot-${key}-help">${help}</p>`:''}<p id="pilot-${key}-error" class="pilot-field-error" hidden></p></div>`;
const deviceImage=(d,eager=false)=>d?.image?`<img src="${e(d.image)}" width="${e(d.imageWidth || 1200)}" height="${e(d.imageHeight || 900)}" alt="${e(d.name)} — ${e(d.imageCaption || 'maker product image')}" loading="${eager?'eager':'lazy'}" decoding="async">`:`<span>${e(d?.name || 'Hardware reference')}</span>`;

export function makerPilotBody(devices) {
  const scout=devices.find(d=>d.slug==='scout-lite'),flipper=devices.find(d=>d.slug==='flipper-zero');
  const example=scout&&flipper?`<article class="pilot-example" id="pilot-example" aria-labelledby="pilot-example-title">
    <div class="pilot-example-header"><span>Example companion page</span><span class="pilot-example-badge">From maker sources</span></div>
    <div class="pilot-example-photo">${deviceImage(scout,true)}</div>
    <div class="pilot-example-content"><p class="pilot-kicker">${e(scout.maker)} · ${e(scout.name)}</p><h2 id="pilot-example-title">${e(scout.usage.goodFor.replace(/\.$/,''))}.</h2><p class="pilot-example-note">${e(scout.usage.tradeoff)}</p>
      <div class="pilot-example-parts">${[[scout,'Expansion board'],[flipper,'Required host · sold separately']].map(([d,role])=>`<a href="/devices/${e(d.slug)}/"><span class="pilot-part-image">${deviceImage(d)}</span><span><strong>${e(d.name)}</strong><small>${role}</small></span>${arrow}</a>`).join('')}</div>
      <details class="pilot-disclosure"><summary>Firmware & setup notes</summary><div><p>${e(scout.usage.needs)}</p><p>Confirm your hardware revision and installation path in the maker’s guide before combining parts.</p><a class="pilot-text-link" href="https://github.com/pingequalab/scout-lite" target="_blank" rel="noopener noreferrer">PINGEQUA user guide ${arrow}</a></div></details>
      <a class="pilot-button pilot-button-ink pilot-example-store" href="${e(scout.source)}" target="_blank" rel="noopener noreferrer">Check Scout Lite at the maker ${arrow}</a>
      <p class="pilot-example-credit">Illustrative layout · source-based, not commissioned or independently hardware-tested. No partner offer or affiliate commission.</p>
      <a class="pilot-text-link" href="/builds/scout-lite/">Explore the companion page ${arrow}</a><details class="pilot-disclosure pilot-photo-credit"><summary>Sources & photo credits</summary><div><a href="${e(scout.source)}" target="_blank" rel="noopener noreferrer">Scout Lite facts · PINGEQUA</a><a href="${e(flipper.source)}" target="_blank" rel="noopener noreferrer">Flipper Zero facts · Flipper Devices</a>${[scout,flipper].filter(d=>d.image).map(d=>`<a href="${e(d.imageSourcePage || d.source)}" target="_blank" rel="noopener noreferrer">${e(d.imageCredit || d.maker)} · ${e(d.name)} photo</a>`).join('')}</div></details>
    </div>
  </article>`:'';
  return `<main id="main" class="maker-pilot shell">
    <section class="pilot-hero" aria-labelledby="pilot-title"><div class="pilot-hero-copy"><p class="pilot-kicker">For hardware makers & creators</p><h1 id="pilot-title">Make the next <br>click useful.</h1><p class="pilot-lede">Turn your gadget demo into a page people can build and buy from. The parts, the setup, and a clear path to your store.</p><div class="pilot-hero-actions"><a class="pilot-button pilot-button-ink" href="#pilot-brief">Prepare a pilot brief ${arrow}</a><a class="pilot-text-link" href="/builds/scout-lite/">See the example ${arrow}</a></div><p class="pilot-hero-note">Your media. Your credit. Your existing audience.</p></div>${example}</section>
    <section class="pilot-offer" aria-labelledby="pilot-offer-title"><div class="pilot-offer-intro"><p class="pilot-kicker">One focused production</p><h2 id="pilot-offer-title">Ready for your <br>next post.</h2><p>You supply the approved demo and product details. We put the useful next steps together.</p><div class="pilot-price"><strong>$750</strong><span>Proposed pilot price <br>One time</span></div></div><div class="pilot-deliverables"><div><span class="pilot-deliverable-number">01</span><div><h3>Your companion page</h3><p>A mobile-friendly page and editable files, with your store links and creator credit.</p></div></div><div><span class="pilot-deliverable-number">02</span><div><h3>The exact starting point</h3><p>Parts, revision, firmware references and a downloadable checklist. Missing details stay visible.</p></div></div><div><span class="pilot-deliverable-number">03</span><div><h3>Something worth sharing</h3><p>One design in three crops, made from your approved images, plus a reusable caption.</p></div></div><details class="pilot-disclosure"><summary>What the pilot includes</summary><div><p>One existing product or build. Up to six catalog devices plus stated accessories, one firmware/revision path, and eight primary-source references. One existing demo and up to five supplied images.</p><p>Five working days of production after complete materials and scope agreement. One consolidated review. Static files and Markdown parts export included; hosting is agreed separately.</p><p>Proposed payments: $375 after scope agreement, $375 after acceptance. Source checks and approved media; new hardware testing, filming and promised audience reach need a different scope.</p><p>Only merchant-approved codes and offers are used. You keep your media ownership and existing links. Reuse rights, review details and acceptance criteria are agreed before payment.</p></div></details></div></section>
    <section id="pilot-brief" class="pilot-brief-section" aria-labelledby="pilot-brief-title"><div class="pilot-brief-intro"><p class="pilot-kicker">Start with one idea</p><h2 id="pilot-brief-title">What are you <br>working on?</h2><p>Prepare a short brief to review or share. The three essentials are enough to start.</p><p class="pilot-local-note">This draft stays in your browser. Copying or downloading it does not send it to us.</p><a class="pilot-text-link" href="/setup/">Just want to share your setup? ${arrow}</a></div>
      <form id="maker-pilot-form" class="pilot-form" novalidate><fieldset id="pilot-fields" disabled><legend class="sr-only">Prepare a maker pilot brief</legend>
        ${field('company','Maker or creator name',{required:true,placeholder:'Your company, project or creator name'})}
        ${field('productURL','Product or build link',{required:true,type:'url',placeholder:'https://…'})}
        ${field('outcome','What should someone be able to do?',{required:true,multiline:true,placeholder:'One useful thing your hardware or build makes possible…'})}
        <details class="pilot-disclosure pilot-extra-fields" id="pilot-extra-fields"><summary>Add project details <span>Optional</span></summary><div>
          ${field('viewer','Who is it for?',{multiline:true,placeholder:'The viewer, and the post or demo they will come from…'})}
          ${field('mediaURL','Photo or demo link',{type:'url',placeholder:'https://…',help:'Link to existing media. No upload is needed.'})}
          <div class="pilot-field"><label for="pilot-mediaRights">Can we reuse the media?</label><select id="pilot-mediaRights" name="mediaRights">${options(MEDIA_RIGHTS)}</select><p class="pilot-field-help">The owner’s permission is needed before production.</p></div>
          ${field('parts','Parts, revision & firmware',{multiline:true,placeholder:'Exact parts, required accessories, firmware version, and anything still to confirm…'})}
          ${field('storeURL','Official store link',{type:'url',placeholder:'https://…'})}
          ${field('dealNotes','Approved offer, if you have one',{multiline:true,placeholder:'Issuer, code or offer link, eligible products, dates, regions and restrictions…',help:'An offer is optional. A note here does not create a partnership or verify a code.'})}
          <div class="pilot-field"><label for="pilot-budget">Budget</label><select id="pilot-budget" name="budget">${options(PILOT_BUDGETS)}</select><p class="pilot-field-help">The proposed pilot is $750. This is a discussion, not an order.</p></div>
          ${field('timing','Preferred timing',{placeholder:'A launch date or a flexible window…'})}
        </div></details>
        <p class="pilot-form-error" id="pilot-form-error" role="alert" hidden></p><div class="pilot-form-actions"><button class="pilot-button pilot-button-ink" type="button" id="pilot-copy">Copy brief ${arrow}</button><button class="pilot-button pilot-button-outline" type="button" id="pilot-download">Download brief</button></div><p class="pilot-save-state" id="pilot-save-state" role="status" aria-live="polite">Preparing local draft…</p><p class="pilot-action-state" id="pilot-action-state" role="status" aria-live="polite"></p>
      </fieldset><noscript><p class="pilot-local-note">JavaScript is needed to prepare and save a local brief. The offer and example above remain readable.</p></noscript></form>
    </section>
    <dialog id="pilot-copy-dialog" class="pilot-copy-dialog" aria-labelledby="pilot-copy-title"><form method="dialog"><h2 id="pilot-copy-title">Copy your brief</h2><p>Automatic copying is unavailable. Select and copy the text below, or use Download brief.</p><label class="sr-only" for="pilot-copy-text">Your complete pilot brief</label><textarea id="pilot-copy-text" readonly rows="14"></textarea><button class="pilot-button pilot-button-ink" type="submit">Done</button></form></dialog>
    <script type="module" src="/maker-pilot.js"></script>
  </main>`;
}
