import { escapeHTML as e, statuses } from './catalog.mjs';
import { kitURL } from './kits.mjs';

export const BUILD_ROUTE = '/builds/lilyshark/';
export const repository = 'https://github.com/maxmoneycash/lilyshark';
const arrow = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>';
const play = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="m9 5 10 7-10 7z"/></svg>';
const photo = (name='traffic', eager=false) => `<img src="/builds/lilyshark/tdeck-${name}.jpg" alt="LilyShark running on a LILYGO T-Deck held in front of a laptop${name==='traffic'?' — the photographed traffic screen uses simulated data':''}" width="1050" height="1400" loading="${eager?'eager':'lazy'}" ${eager?'fetchpriority="high"':''}>`;

function hardwareImage(d, eager=false) {
  return `<img src="${e(d.image)}" alt="${e(d.name)} — ${e(d.imageCaption)}" width="${d.imageWidth}" height="${d.imageHeight}" loading="${eager?'eager':'lazy'}" decoding="async">`;
}
function discoveryCard(d, title, text, type='') {
  return `<article class="discovery-card ${type}"><a class="discovery-card-image" href="/devices/${d.slug}/" tabindex="-1" aria-hidden="true">${hardwareImage(d)}<span>${e(statuses[d.status])}</span></a><div class="discovery-card-copy"><h3><a href="/devices/${d.slug}/">${e(d.name)} ${arrow}</a></h3><p>${e(title)}</p></div></article>`;
}

export function discoveryHome(devices) {
  const get = slug => devices.find(d=>d.slug===slug);
  return `<main id="main" class="workbench-home shell">
    <div class="home-heading"><h1>Hardware to <br>make your own.</h1><form action="/hardware/" class="home-search" role="search"><label class="sr-only" for="home-search">Search hardware</label><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg><input type="search" name="q" id="home-search" placeholder="Find hardware…" maxlength="200"><button type="submit" aria-label="Search hardware">${arrow}</button></form></div>
    <nav class="discovery-topics" aria-label="Discover by interest"><a href="/hardware/?task=radio">Radio experiments</a><a href="/hardware/?task=mesh">Off-grid messaging</a><a href="/hardware/?task=computers">Pocket computers</a><a href="/hardware/?task=build">Build & code</a><a href="/hardware/">All hardware ${arrow}</a></nav>
    <section class="discovery-lead" aria-label="Featured build and hardware discoveries">
      <article class="lead-build"><a class="lead-build-photo" href="${BUILD_ROUTE}" tabindex="-1" aria-hidden="true">${photo('traffic',true)}<span class="image-credit">Project photo · simulated display</span></a><div class="lead-build-copy"><span class="feature-label">Featured build · LilyShark</span><div><h2><a href="${BUILD_ROUTE}">A radio lab.<br> In your hand.</a></h2><p>Open-source radio firmware for the T-Deck.</p></div><div class="feature-actions"><a class="wb-button wb-button-light" href="${BUILD_ROUTE}">Explore the build ${arrow}</a></div><span class="feature-status">Developer alpha</span></div></article>
      <div class="lead-discoveries">${discoveryCard(get('ggtag'),'A badge you program with sound.','An e-paper display with an unexpected way to get your message across.','compact-discovery')}${discoveryCard(get('pocketmage'),'A tiny computer. A real keyboard.','E-paper, a folding case, and a different idea of portable computing.','compact-discovery')}</div>
    </section>
    <section class="closer-look" aria-labelledby="closer-look-title"><div class="workbench-section-title"><h2 id="closer-look-title">Good things to build with.</h2><a class="object-link" href="/hardware/">All ${devices.length} devices ${arrow}</a></div><div class="discovery-object-grid">${[
      ['sensor-watch-pro','Give a familiar watch a new brain.','A programmable replacement board. Watch case sold separately.'],
      ['radiacode-110','Take a closer look at the invisible.','A pocket gamma spectrometer with a very particular job.'],
      ['nibble','Build the console. Then the game.','A solder-it-yourself handheld you can program.'],
      ['catsniffer-v3','Put low-power radio on your bench.','A USB board for supported wireless protocol experiments.']
    ].map(([slug,title,text])=>discoveryCard(get(slug),title,text)).join('')}</div></section>
    <section class="make-something"><h2>Show what you made.</h2><a class="wb-button wb-button-ink" href="/setup/">Create a setup ${arrow}</a></section>
  </main>`;
}

export function lilysharkBuild(devices) {
  const d=devices.find(d=>d.slug==='lilygo-t-deck-plus');
  const remix=kitURL({name:'My LilyShark radio workbench',author:'LilyShark',story:'A starting point for a T-Deck running LilyShark. Add your hardware revision, firmware version and what you tested.',parts:'USB data cable; antenna matched to the radio band. MicroSD capture writes remain unverified on hardware.',project:repository,devices:[d.slug]});
  return `<main id="main" class="build-main shell">
    <nav class="build-breadcrumb" aria-label="Breadcrumb"><a href="/builds/">Builds</a><span aria-hidden="true">/</span><span>LilyShark</span></nav>
    <article>
      <header class="project-hero"><figure class="project-photo">${photo('traffic',true)}<figcaption>LilyShark project photo · simulated traffic display.</figcaption></figure><div class="project-intro"><p class="overline">LilyShark</p><h1>A radio lab.<br> In your hand.</h1><p class="project-lede">A handheld workspace for mesh radio traffic, built on the LILYGO T-Deck.</p><div class="project-author"><span class="author-monogram" aria-hidden="true">LS</span><span><strong>By the LilyShark project</strong><small>LilyShark firmware · LILYGO hardware</small></span><span class="alpha-label">Developer alpha</span></div><div class="project-actions"><a class="wb-button wb-button-ink" href="#demo">${play} Try the capture demo</a><button type="button" class="wb-button wb-button-outline" data-share-build>Copy build link ${arrow}</button></div></div></header>
      <nav class="project-nav" aria-label="Build sections"><a href="#demo">Try it</a><a href="#how-it-works">How it works</a><a href="#parts">Parts & setup</a><a href="#build-evidence">What’s verified</a></nav>
      <section id="demo" class="project-section demo-section" aria-labelledby="demo-heading"><div class="workbench-section-title"><div><p class="overline">GET A FEEL FOR IT</p><h2 id="demo-heading">Explore a capture.</h2></div><span class="sample-badge">Synthetic sample</span></div><p class="section-lede">24 synthetic frames. Choose one to inspect its signal, integrity and bytes.</p>
      <div class="capture-demo" data-capture-demo><div class="demo-toolbar"><div class="demo-filename"><span aria-hidden="true">▤</span><strong>lilyshark-synthetic.lscap</strong><span>24 frames</span></div><a href="/samples/lilyshark-synthetic.lscap" download class="demo-download">Download capture ${arrow}</a></div><div class="demo-challenges" role="group" aria-label="Inspect the capture"><button type="button" data-capture-filter="all" aria-pressed="true">All frames</button><button type="button" data-capture-filter="crc" aria-pressed="false">Find the CRC failure</button><button type="button" data-capture-filter="truncated" aria-pressed="false">Find the truncated frame</button></div><p class="demo-loading" id="capture-message" role="status">Loading the synthetic capture…</p><button type="button" id="capture-retry" class="wb-button wb-button-outline" hidden>Try loading again</button><div class="capture-workspace" id="capture-workspace" hidden><div class="capture-list-panel"><div class="capture-columns" aria-hidden="true"><span>Frame / elapsed</span><span>Signal</span><span>CRC</span></div><div id="capture-frames" class="capture-frames" role="group" aria-label="Capture frames"></div></div><section class="packet-inspector" id="packet-inspector" aria-labelledby="packet-title"><div class="inspector-heading"><div><p class="overline">SELECTED FRAME</p><h3 id="packet-title"></h3></div><span class="packet-state" id="packet-state"></span></div><p id="packet-explanation"></p><dl id="packet-measurements" class="packet-measurements"></dl><details class="packet-bytes"><summary>Raw bytes <span id="packet-byte-count"></span></summary><pre id="packet-hex" tabindex="0" aria-label="Selected frame raw bytes"></pre></details><p class="packet-provenance">Generated fixture · not over-the-air traffic</p></section></div><noscript><p class="demo-static-note">The packet inspector needs JavaScript. You can download the capture and inspect it with the open-source tools.</p></noscript></div>
      <p class="demo-note">Generated data only; this demo does not connect to a radio. <a href="${repository}/blob/main/scripts/generate_sample_capture.py" target="_blank" rel="noopener noreferrer">How the sample is generated ↗</a></p></section>
      <div class="build-editorial-grid"><div class="build-prose"><section id="how-it-works" class="project-section"><p class="overline">THE IDEA</p><h2>How it works</h2><p>LilyShark shows a frame’s bytes, timing, signal strength and CRC status.</p><ol class="build-steps"><li><span>01</span><div><h3>Tune the radio</h3><p>Match the frequency, bandwidth and spreading factor. The SX1262 listens on one channel at a time.</p></div></li><li><span>02</span><div><h3>Inspect a frame</h3><p>Check the bytes and RF measurements. Decoding depends on the profile; private payloads still need keys.</p></div></li><li><span>03</span><div><h3>Keep the capture</h3><p>Capture files preserve bytes and metadata for the companion tools.</p></div></li></ol><a class="object-link" href="${repository}" target="_blank" rel="noopener noreferrer">Explore the source code ${arrow}</a></section>
      <details id="build-evidence" class="info-disclosure"><summary><h2>Development status</h2><span>Developer alpha</span></summary><div class="disclosure-copy"><div class="evidence-entry"><span class="evidence-dot" aria-hidden="true"></span><div><h3>Recorded in the project</h3><p>The repository records live Meshtastic reception, decoding and two-way direct messages between two T-Deck Plus units. These are prior project observations.</p></div></div><div class="evidence-entry"><span class="evidence-dot pending" aria-hidden="true"></span><div><h3>Still needs hardware validation</h3><p>MicroSD capture writes, spectrum-scan recovery and live MeshCore / Reticulum paths remain unverified. The sample above cannot establish any of these.</p></div></div><a class="object-link" href="${repository}#project-status" target="_blank" rel="noopener noreferrer">Read the development status ${arrow}</a><p class="version-note">Checked September 15, 2026. Follow the repository for firmware targets and installation.</p></div></details></div>
      <aside id="parts" class="build-parts"><div class="parts-heading"><h2>Parts & setup</h2></div><a class="parts-device" href="/devices/${d.slug}/">${hardwareImage(d)}<span><strong>${e(d.name)}</strong><small>Hardware by ${e(d.maker)}</small></span>${arrow}</a><ul class="parts-list"><li><span>LilyShark firmware</span><strong>Open source</strong></li><li><span>USB data cable</span><strong>Required for flashing</strong></li><li><span>Band-matched antenna</span><strong>Check your hardware</strong></li><li><span>MicroSD card</span><strong>Capture path unverified</strong></li></ul><a class="wb-button wb-button-ink" href="${e(d.source)}" target="_blank" rel="noopener noreferrer">Check hardware at LILYGO ${arrow}</a><a class="wb-button wb-button-outline" href="${repository}/blob/main/docs/FLASHING.md" target="_blank" rel="noopener noreferrer">Read the flashing guide ${arrow}</a><p class="parts-note">Confirm band, revision, accessories and stock with LILYGO. No affiliate commission.</p><div class="remix-prompt"><a class="object-link" href="${e(remix)}">Make your own setup ${arrow}</a></div></aside></div>
      <section class="next-build"><div><h2>What’s next?</h2><p>An original LilyShark board and enclosure. Still a concept.</p></div><a class="object-link" href="/devices/lilyshark/">See the hardware direction ${arrow}</a></section>
    </article>
    <div id="build-share-fallback" class="build-share-fallback" hidden><label for="build-share-url">Copy this build’s address</label><input id="build-share-url" type="url" readonly><p>This local preview link opens on this machine. Public sharing needs a hosted site.</p></div>
    <script type="module" src="/capture-demo.js"></script>
  </main>`;
}
