#!/usr/bin/env python3
"""Bake .rgb565 field tiles into a C source file so the T-Deck shows imagery
without a microSD card.

The device's tile loader reads /maps/*.rgb565 off the SD card. A demo should
not depend on a card being present and populated, so the tiles for one place
are compiled into flash instead. SD is still tried first, so a card can always
override or extend what is baked in.
"""
import argparse
import glob
import os
import re
import sys

TILE_BYTES = 320 * 204 * 2  # kSatelliteWidth * kSatelliteHeight * 2

NAME_RE = re.compile(r"(?P<kind>sat|dark)_(?P<lat>-?\d+\.\d{3})_(?P<lon>-?\d+\.\d{3})_z(?P<zoom>\d+)\.rgb565$")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--maps-dir", default="assets/maps")
    ap.add_argument("--out", required=True)
    ap.add_argument("--lat", type=float, required=True, help="cell latitude, 3dp")
    ap.add_argument("--lon", type=float, required=True, help="cell longitude, 3dp")
    args = ap.parse_args()

    want_lat = f"{args.lat:.3f}"
    want_lon = f"{args.lon:.3f}"

    tiles = []
    for path in sorted(glob.glob(os.path.join(args.maps_dir, "*.rgb565"))):
        m = NAME_RE.search(os.path.basename(path))
        if not m:
            continue
        if m.group("lat") != want_lat or m.group("lon") != want_lon:
            continue
        size = os.path.getsize(path)
        if size != TILE_BYTES:
            print(f"skip {path}: {size} bytes, expected {TILE_BYTES}", file=sys.stderr)
            continue
        tiles.append((m.group("kind"), int(m.group("zoom")), path))

    if not tiles:
        print(f"no tiles for {want_lat},{want_lon} in {args.maps_dir}", file=sys.stderr)
        return 1

    out = []
    out.append("// Generated by scripts/embed_map_tiles.py. Do not edit.")
    out.append(f"// Baked field imagery for {want_lat}, {want_lon} — {len(tiles)} tile(s).")
    out.append("//")
    out.append("// The loader tries microSD first; these are the fallback so the map shows")
    out.append("// imagery on a device with no card in it.")
    out.append("")
    out.append("// Only the device build needs these: the simulator reads")
    out.append("// assets/maps/*.rgb565 straight off disk.")
    out.append("#if defined(LILYSHARK_DEVICE)")
    out.append("")
    out.append("#include <cstdint>")
    out.append("#include <cstddef>")
    out.append("")
    out.append("namespace lilyshark {")
    out.append("namespace {")
    out.append("")

    symbols = []
    for kind, zoom, path in tiles:
        sym = f"kTile_{kind}_z{zoom}"
        symbols.append((kind, zoom, sym))
        with open(path, "rb") as fh:
            payload = fh.read()
        words = len(payload) // 2
        out.append(f"// {os.path.basename(path)} ({len(payload)} bytes)")
        out.append(f"const std::uint16_t {sym}[{words}] = {{")
        row = []
        chunks = []
        for i in range(words):
            # The file is little-endian RGB565, matching the LVGL buffer.
            value = payload[i * 2] | (payload[i * 2 + 1] << 8)
            row.append(f"0x{value:04x}")
            if len(row) == 16:
                chunks.append("," .join(row))
                row = []
        if row:
            chunks.append(",".join(row))
        out.append(",\n".join(chunks))
        out.append("};")
        out.append("")

    out.append("struct BakedTile {")
    out.append("    const char *kind;")
    out.append("    int zoom;")
    out.append("    const std::uint16_t *pixels;")
    out.append("};")
    out.append("")
    out.append("const BakedTile kBakedTiles[] = {")
    for kind, zoom, sym in symbols:
        out.append(f'    {{"{kind}", {zoom}, {sym}}},')
    out.append("};")
    out.append("")
    out.append("} // namespace")
    out.append("")
    out.append(f"const double kBakedTileLat = {want_lat};")
    out.append(f"const double kBakedTileLon = {want_lon};")
    out.append("")
    out.append("/// Where the baked imagery is, so a device with no GPS fix can still")
    out.append("/// show its operating area instead of an empty grid.")
    out.append("double bakedMapTileLat() noexcept { return kBakedTileLat; }")
    out.append("double bakedMapTileLon() noexcept { return kBakedTileLon; }")
    out.append("bool hasBakedMapTiles() noexcept { return true; }")
    out.append("")
    out.append("/// Baked pixels for this cell, or nullptr when nothing matches.")
    out.append("const std::uint16_t *bakedMapTile(const char *kind, double cell_lat,")
    out.append("                                  double cell_lon, int zoom) noexcept")
    out.append("{")
    out.append("    if (kind == nullptr) return nullptr;")
    out.append("    // Cell coordinates are already rounded to 3dp by the caller.")
    out.append("    if (cell_lat < kBakedTileLat - 0.0005 || cell_lat > kBakedTileLat + 0.0005) return nullptr;")
    out.append("    if (cell_lon < kBakedTileLon - 0.0005 || cell_lon > kBakedTileLon + 0.0005) return nullptr;")
    out.append("    for (std::size_t i = 0; i < sizeof(kBakedTiles) / sizeof(kBakedTiles[0]); ++i) {")
    out.append("        const BakedTile &tile = kBakedTiles[i];")
    out.append("        if (tile.zoom != zoom) continue;")
    out.append("        if (tile.kind[0] != kind[0]) continue;")
    out.append("        return tile.pixels;")
    out.append("    }")
    out.append("    return nullptr;")
    out.append("}")
    out.append("")
    out.append("} // namespace lilyshark")
    out.append("")
    out.append("#endif // LILYSHARK_DEVICE")
    out.append("")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as fh:
        fh.write("\n".join(out))
    print(f"wrote {args.out}: {len(tiles)} tiles, ~{len(tiles) * TILE_BYTES // 1024} kB of flash")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
