#!/usr/bin/env python3
"""Generate Lilyshark's native-size LVGL A8 wordmark asset."""

import hashlib
import subprocess
import sys
import tempfile
from pathlib import Path


WIDTH = 264
HEIGHT = 128
EXPECTED_RSVG_VERSION = "2.61.3"
EXPECTED_PILLOW_VERSION = "10.4.0"

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE = REPO_ROOT / "assets/brand/lilyshark-wordmark-pink.svg"
OUTPUT = REPO_ROOT / "src/ui/assets/lilyshark_wordmark_a8.c"


def fail(message):
    raise SystemExit(message)


def renderer_version():
    try:
        result = subprocess.run(
            ["rsvg-convert", "--version"],
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        fail("rsvg-convert is required to regenerate the device logo asset")
    except subprocess.CalledProcessError as error:
        fail("rsvg-convert --version failed: {}".format(error))

    first_line = result.stdout.splitlines()[0] if result.stdout else ""
    expected = "rsvg-convert version {}".format(EXPECTED_RSVG_VERSION)
    if first_line != expected:
        fail("expected '{}', found '{}'".format(expected, first_line or "no version"))
    return EXPECTED_RSVG_VERSION


def render_alpha():
    try:
        import PIL
        from PIL import Image
    except ImportError:
        fail(
            "Pillow {} is required; run: uv run --with Pillow=={} {}".format(
                EXPECTED_PILLOW_VERSION, EXPECTED_PILLOW_VERSION, Path(__file__).name
            )
        )

    if PIL.__version__ != EXPECTED_PILLOW_VERSION:
        fail(
            "expected Pillow {}, found {}".format(
                EXPECTED_PILLOW_VERSION, PIL.__version__
            )
        )

    with tempfile.TemporaryDirectory(prefix="lilyshark-logo-") as temp_dir:
        rendered = Path(temp_dir) / "wordmark.png"
        subprocess.run(
            [
                "rsvg-convert",
                "--width",
                str(WIDTH),
                "--height",
                str(HEIGHT),
                "--keep-aspect-ratio",
                "--output",
                str(rendered),
                str(SOURCE),
            ],
            check=True,
        )
        with Image.open(rendered) as image:
            rgba = image.convert("RGBA")
            if rgba.size != (WIDTH, HEIGHT):
                fail("renderer returned {} instead of {}x{}".format(rgba.size, WIDTH, HEIGHT))
            return bytes(rgba.getchannel("A").getdata())


def format_bytes(data):
    rows = []
    for offset in range(0, len(data), 16):
        values = ", ".join("0x{:02x}".format(value) for value in data[offset : offset + 16])
        rows.append("    {},".format(values))
    return "\n".join(rows)


def generated_source(alpha, rsvg_version):
    source_sha = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    alpha_sha = hashlib.sha256(alpha).hexdigest()
    return """// Generated by scripts/generate_logo_asset.py. Do not edit by hand.
// SPDX-License-Identifier: GPL-3.0-only
// Source: assets/brand/lilyshark-wordmark-pink.svg
// Source SHA-256: {source_sha}
// Alpha SHA-256: {alpha_sha}
// Renderer: librsvg {rsvg_version}; Pillow {pillow_version}

#include "lilyshark/ui/assets/lilyshark_wordmark_a8.h"

static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t
lilyshark_wordmark_a8_map[] = {{
{data}
}};

const lv_image_dsc_t lilyshark_wordmark_a8 = {{
    .header.cf = LV_COLOR_FORMAT_A8,
    .header.w = LILYSHARK_WORDMARK_A8_WIDTH,
    .header.h = LILYSHARK_WORDMARK_A8_HEIGHT,
    .header.stride = LILYSHARK_WORDMARK_A8_STRIDE,
    .data_size = sizeof(lilyshark_wordmark_a8_map),
    .data = lilyshark_wordmark_a8_map,
}};
""".format(
        source_sha=source_sha,
        alpha_sha=alpha_sha,
        rsvg_version=rsvg_version,
        pillow_version=EXPECTED_PILLOW_VERSION,
        data=format_bytes(alpha),
    )


def main():
    if not SOURCE.is_file():
        fail("logo source is missing: {}".format(SOURCE))

    version = renderer_version()
    alpha = render_alpha()
    if len(alpha) != WIDTH * HEIGHT:
        fail("A8 payload has {} bytes, expected {}".format(len(alpha), WIDTH * HEIGHT))

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated_source(alpha, version), encoding="utf-8")
    print("generated {} ({} bytes A8)".format(OUTPUT.relative_to(REPO_ROOT), len(alpha)))


if __name__ == "__main__":
    main()
