#!/usr/bin/env python3
"""Regenerate the Most-Wanted Cells list from Field Receipts scorer data.

Flightradar24 publishes "most wanted receiver locations"; Hivemapper's
live gap map steers drivers to unmapped roads. Most-wanted cells are the
same mechanism over Field Receipts: empty or stale cells adjacent to
verified active ones, ranked by adjacent active density, so contributors
know where an analyzer run or field survey provides the highest network value.

Outputs:
- docs/most-wanted.md (dated markdown table for repo readers)
- webapp/public/most-wanted.json (machine-readable feed for lilyshark.com)
- webapp/public/most-wanted.md (copy for the webapp)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = REPO_ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

import field_receipts_score as frs  # noqa: E402

DEFAULT_RULES = REPO_ROOT / "docs" / "protocol" / "season-0-rules.json"
DEFAULT_EVENTS = REPO_ROOT / "analysis" / "fixtures" / "season_0_events.json"
DEFAULT_CELLS = REPO_ROOT / "analysis" / "fixtures" / "season_0_cells.json"
DEFAULT_OUT_MD = REPO_ROOT / "docs" / "most-wanted.md"
DEFAULT_OUT_JSON = REPO_ROOT / "webapp" / "public" / "most-wanted.json"
DEFAULT_WEB_MD = REPO_ROOT / "webapp" / "public" / "most-wanted.md"


def generate_most_wanted(
    events_path: Path,
    cells_path: Path,
    rules_path: Path = DEFAULT_RULES,
    stale_after_weeks: int = 4,
    as_of: str | None = None,
    limit: int = 50,
) -> tuple[dict, str]:
    rules, rules_sha256 = frs.load_rules(rules_path)
    events = frs.load_events(events_path)
    cell_records = frs.load_cell_records(cells_path)
    output = frs.build_most_wanted(
        events, cell_records, rules, rules_sha256,
        stale_after_weeks, as_of, limit
    )

    method = output["method"]
    lines = [
        f"# Most-Wanted Cells — Week {method['as_of_week']}",
        "",
        "> [!NOTE]",
        f"> Cells adjacent to verified activity with no verified capture in the last "
        f"{method['stale_after_weeks']} weeks. Generated by "
        f"`scripts/generate_most_wanted.py` from public receipts. "
        f"Active verified cells: **{method['active_cell_count']}**, "
        f"Total verified cells: **{method['verified_cell_count']}**.",
        "",
        "| Cell (Geohash-5) | Band | Adjacent active | Last surveyed | Priority |",
        "| --- | --- | ---: | --- | --- |",
    ]
    for row in output["most_wanted"]:
        adj = row["adjacent_active_cells"]
        last_survey = row["last_surveyed_week"] or "never"
        priority = "Highest" if adj >= 3 else ("High" if adj == 2 else "Medium")
        lines.append(
            f"| `{row['geohash5']}` | {row['band']} "
            f"| {adj} | {last_survey} | {priority} |"
        )
    markdown = "\n".join(lines) + "\n"
    return output, markdown


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the most-wanted cells publication from scorer data."
    )
    parser.add_argument("--events", type=Path, default=DEFAULT_EVENTS,
                        help="Path to chain events JSON extract")
    parser.add_argument("--cells", type=Path, default=DEFAULT_CELLS,
                        help="Path to cell sidecar metadata records JSON")
    parser.add_argument("--rules", type=Path, default=DEFAULT_RULES,
                        help="Path to pinned season rules JSON")
    parser.add_argument("--output-md", type=Path, default=DEFAULT_OUT_MD,
                        help="Output path for the Markdown document")
    parser.add_argument("--output-json", type=Path, default=DEFAULT_OUT_JSON,
                        help="Output path for the JSON feed")
    parser.add_argument("--stale-after-weeks", type=int, default=4,
                        help="Weeks without verified survey before cell is stale (default: 4)")
    parser.add_argument("--as-of", type=str, default=None,
                        help="ISO week YYYY-Www (default: newest in data)")
    parser.add_argument("--limit", type=int, default=50,
                        help="Maximum most-wanted cells to list (default: 50)")
    parser.add_argument("--check", action="store_true",
                        help="Verify output files are up to date without writing")

    args = parser.parse_args(argv)

    if not args.events.exists() or not args.cells.exists():
        sys.stderr.write(f"Missing input fixtures: {args.events} or {args.cells}\n")
        return 1

    output, markdown = generate_most_wanted(
        args.events, args.cells, args.rules,
        args.stale_after_weeks, args.as_of, args.limit
    )

    json_str = json.dumps(output, indent=2, sort_keys=True) + "\n"

    if args.check:
        if not args.output_md.exists() or not args.output_json.exists():
            sys.stderr.write("Most-wanted publications missing; run without --check to generate.\n")
            return 1
        if args.output_md.read_text(encoding="utf-8") != markdown:
            sys.stderr.write(f"{args.output_md} is out of date.\n")
            return 1
        if args.output_json.read_text(encoding="utf-8") != json_str:
            sys.stderr.write(f"{args.output_json} is out of date.\n")
            return 1
        print("Most-wanted publications are up to date.")
        return 0

    args.output_md.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_md.write_text(markdown, encoding="utf-8")
    args.output_json.write_text(json_str, encoding="utf-8")

    # Also mirror to webapp/public/most-wanted.md if webapp/public exists
    if DEFAULT_WEB_MD.parent.exists():
        DEFAULT_WEB_MD.write_text(markdown, encoding="utf-8")

    print(f"Wrote {args.output_md}")
    print(f"Wrote {args.output_json}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
