#!/usr/bin/env python3
"""Regenerate LXMF fixtures with the reference stack, without sending packets.

Run: uv run --no-project --with lxmf==1.1.1 --with rns==1.5.2 \
         python test/lxmf/generate_fixtures.py

The fixed private key is public test material. Signatures are deterministic;
the optional stamp is synthetic and tests parsing, not proof-of-work validity.
"""

from pathlib import Path
import tempfile

import LXMF
import RNS
from RNS.vendor import umsgpack


def array(name, data):
    lines = [f"inline constexpr std::uint8_t {name}[] = {{"]
    for offset in range(0, len(data), 12):
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in data[offset:offset + 12]) + ",")
    return "\n".join(lines + ["};\n"])


def main():
    assert LXMF.__version__ == "1.1.1" and RNS.__version__ == "1.5.2"
    header = bytes(range(0x10, 0x20)) + bytes(range(0x20, 0x30))
    header += bytes((i * 3) & 0xFF for i in range(64))
    cases = [
        ("kLxmfPlain", [1771200000.5, b"TRAIL REPORT", b"TRACK IS WASHED OUT PAST THE CREEK", {1: b"x", 2: 7}]),
        ("kLxmfEmpty", [0.0, b"", b"", {}]),
        ("kLxmfNils", [1.0, None, None, None]),
        ("kLxmfShortArray", [1.0, b"a", b"b"]),
        ("kLxmfLongContent", [2.0, b"", b"L" * 300, {}]),
        ("kLxmfControlBytes", [3.0, b"", b"A\x00B\x1bC\nD", {}]),
        ("kLxmfNestedFields", [4.0, b"", b"hi", {1: [1, 2, {3: b"deep"}], 2: {4: 5}}]),
    ]
    output = ["// Generated by test/lxmf/generate_fixtures.py; do not hand-edit.\n",
              "#pragma once\n#include <cstdint>\n"]
    output += [array(name, header + umsgpack.packb(payload)) for name, payload in cases]

    with tempfile.TemporaryDirectory(prefix="lilyshark-lxmf-fixtures-") as root:
        Path(root, "config").write_text(
            "[reticulum]\n  enable_transport = False\n  share_instance = False\n"
            "[logging]\n  loglevel = 1\n[interfaces]\n"
        )
        # No interfaces are configured; every packet is packed, never sent.
        RNS.Reticulum(configdir=root)
        identity = RNS.Identity(create_keys=False)
        identity.load_private_key(bytes(range(64)))
        source = RNS.Destination(identity, RNS.Destination.IN, RNS.Destination.SINGLE, "lxmf", "delivery")
        destination = RNS.Destination(None, RNS.Destination.OUT, RNS.Destination.PLAIN, "lilyshark", "test")
        for stamped in (False, True):
            message = LXMF.LXMessage(destination, source, "Heard on 913.125 MHz", title="Field note",
                                     desired_method=LXMF.LXMessage.OPPORTUNISTIC)
            message.timestamp = 1771200000.5
            if stamped:
                message.stamp_cost = 8
                message.stamp = bytes(range(32))
                message.defer_stamp = False
            message.pack()
            payload = umsgpack.unpackb(message.packed[96:])
            assert payload[:4] == [message.timestamp, message.title, message.content, message.fields]
            assert len(payload) == (5 if stamped else 4)
            suffix = "Stamped" if stamped else "Reference"
            output.append(array(f"kLxmf{suffix}", message.packed))
            packet = message._LXMessage__as_packet()
            packet.pack()
            assert packet.data == message.packed[16:]
            # Prefix the clear RNode shim used by the firmware's decoder.
            output.append(array(f"kLxmfRNode{suffix}", b"\x40" + packet.raw))

    Path(__file__).with_name("fixtures.h").write_text("\n".join(output))


if __name__ == "__main__":
    main()
