#!/usr/bin/env python3
"""Counterfactuals: what the capture-and-pointer workflow looks like WITHOUT
content-addressed network storage.

Two small analytic models that make the "why Shelby" question concrete:

  1. Capture survival — the probability a field capture still exists (and is
     provably unchanged) after N years on a microSD card vs on replicated
     network storage. SD cards in field devices fail, get lost, and can be
     edited without detection; a content-addressed replica set fails only if
     every replica is lost, and any alteration is detected on read.

  2. Pointer resolution — a node off-grid hears an 82-byte SHLB pointer. How
     long until some gateway (a node with connectivity) is close enough to
     resolve it? Modeled from domain mixing: with a fraction g of nodes being
     gateways, a 30-node collision domain contains at least one gateway with
     probability 1 - (1 - g)^30.

Everything is an explicit, labeled assumption below — change and rerun. This
is a model of failure modes, not a reliability guarantee.

Deterministic. Writes analysis/results_counterfactuals.md. Stdlib only.
"""

from __future__ import annotations

from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent

# ── Assumptions (labeled; sensitivity shown where it matters) ────────────────
YEARS = [1, 2, 3, 5]

# Consumer microSD in a field device: card failure plus device loss/damage.
# Field reports for consumer cards in write-heavy logging use cluster around
# 5-10%/yr; device attrition (drops, weather, loss) adds its own. We model
# card and device separately and combine.
SD_CARD_FAILURE_YR = 0.06
DEVICE_LOSS_YR = 0.05

# Network storage: an erasure-coded blob survives unless its replica group is
# lost. Model per-replica-group annual loss at 1% (generous to the
# counterfactual: a whole provider set going dark in a year) — and show
# sensitivity at 5%.
REPLICA_GROUP_LOSS_YR = 0.01
REPLICA_GROUP_LOSS_YR_SENSITIVITY = 0.05

# Gateway resolution
NODES_PER_DOMAIN = 30  # from the report's working density
GATEWAY_FRACTIONS = [0.01, 0.02, 0.05, 0.10, 0.20]
CHECK_INS_PER_DAY = 4  # how often a node meets a domain peer (field cadence)


def sd_survival(years: float) -> float:
    """P(a capture on one card in one device survives `years` years)."""
    annual_keep = (1 - SD_CARD_FAILURE_YR) * (1 - DEVICE_LOSS_YR)
    return annual_keep**years


def network_survival(years: float, group_loss: float = REPLICA_GROUP_LOSS_YR) -> float:
    """P(a replicated blob survives `years` years): one group-loss event per
    year would kill it; groups are independent across years."""
    return (1 - group_loss) ** years


def domain_gateway_coverage(g: float) -> float:
    """P(at least one gateway among a node's collision-domain peers)."""
    return 1 - (1 - g) ** NODES_PER_DOMAIN


def expected_days_to_resolution(g: float) -> float:
    coverage = domain_gateway_coverage(g)
    if coverage <= 0:
        return float("inf")
    return 1.0 / (coverage * CHECK_INS_PER_DAY)


def build_report() -> str:
    lines: list[str] = []
    w = lines.append
    w("# Counterfactuals: without content-addressed network storage")
    w("")
    w("Generated by `analysis/counterfactuals.py` — an analytic model of failure")
    w("modes with labeled assumptions, not a reliability guarantee.")
    w("")

    w("## 1. A capture on a card is a capture on borrowed time")
    w("")
    w(f"Assumptions: consumer microSD fails at {SD_CARD_FAILURE_YR:.0%}/yr and a field")
    w(f"device is lost or damaged at {DEVICE_LOSS_YR:.0%}/yr; the network replica group")
    w(f"is lost at {REPLICA_GROUP_LOSS_YR:.0%}/yr (sensitivity at {REPLICA_GROUP_LOSS_YR_SENSITIVITY:.0%}).")
    w("")
    w("| Years | P(survives on microSD) | P(survives replicated) | (replicas at 5% loss) |")
    w("| ---: | ---: | ---: | ---: |")
    for y in YEARS:
        w(
            f"| {y} | {sd_survival(y):.1%} | {network_survival(y):.1%} | "
            f"{network_survival(y, REPLICA_GROUP_LOSS_YR_SENSITIVITY):.1%} |"
        )
    w("")
    w("Two different failure *shapes*: a card's survival decays multiplicatively")
    w("with nothing to check it against, while a content-addressed blob is")
    w("verified on every read — a tampered or rotted copy is detected, not")
    w("silently trusted (`scripts/shelby_pointer.py verify` does exactly this).")
    w("Survival is only half the story; the other half is knowing the bytes are")
    w("the bytes the radio heard.")
    w("")

    w("## 2. How many gateways make off-grid resolution practical?")
    w("")
    w(f"A node's collision domain is ~{NODES_PER_DOMAIN} peers. With a fraction g of")
    w("nodes acting as gateways, the probability the domain contains one, and")
    w(f"the expected time to resolve a heard pointer at {CHECK_INS_PER_DAY} peer")
    w("check-ins/day:")
    w("")
    w("| Gateways in the mesh | P(domain has one) | Expected time to resolve |")
    w("| ---: | ---: | ---: |")
    for g in GATEWAY_FRACTIONS:
        days = expected_days_to_resolution(g)
        pretty = f"{days * 24:.1f} h" if days < 1 else f"{days:.1f} d"
        w(f"| {g:.0%} | {domain_gateway_coverage(g):.1%} | {pretty} |")
    w("")
    w("The knee is around 5%: below it, a pointer can wait a day or more; at and")
    w("above it, resolution is same-day. That is the sizing target for the gateway")
    w("component — and it is cheap to reach, because a gateway is any node with")
    w("connectivity, including the operator's phone when it next has signal.")
    w("")
    return "\n".join(lines)


def main() -> None:
    (OUT_DIR / "results_counterfactuals.md").write_text(build_report())
    print(f"wrote {OUT_DIR / 'results_counterfactuals.md'}")


if __name__ == "__main__":
    main()
